title: Xdev
author: the Xdev Team
copyright: '2022'
logo: images/xdev_logo_light.svg

exclude_patterns:
  - _build
  - Thumbs.db
  - .DS_Store
  - "**.ipynb_checkpoints"
  - README.md

execute:
  execute_notebooks: "off"

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes:
   - mailto
   - http
   - https
  myst_dmath_double_inline: true

sphinx:
  config:
    html_baseurl: "https://ncar-xdev.github.io"
    comments_config:
      utterances:
        repo: ncar-xdev/ncar-xdev-utterances
    html_favicon: images/x_icon_light.png
    html_last_updated_fmt: '%-d %B %Y'
    html_sidebars:
      index: []
    html_theme: sphinx_pythia_theme
    html_theme_options:
      use_edit_page_button: true
      use_repository_button: true
      use_issues_button: true
      google_analytics_id: "G-50ST3W7ZN6"
      home_page_in_toc: true
      github_url: https://github.com/ncar-xdev
      twitter_url: https://twitter.com/NCARXdev
      repository_url: https://github.com/ncar-xdev/ncar-xdev.github.io
      repository_branch: main
      path_to_docs: ""
      page_layouts:
        index: page-banner.html
      navbar_links:
        - name: About
          url: about/index
        - name: Handbook
          url: handbook/index
        - name: Status
          url: status/index
      footer_logos:
        NCAR: images/NCAR-contemp-logo-blue.png
      extra_navbar: |
        Theme by <a href="https://projectpythia.org">Project Pythia</a>,<br>
        powered by <a href="https://jupyterbook.org">Jupyter Book</a>.
