name: nightly

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup miniconda environment
        uses: conda-incubator/setup-miniconda@master
        with:
          channels: conda-forge,nodefaults
          channel-priority: strict
          activate-environment: xdev
          auto-update-conda: false
          python-version: 3.9
          environment-file: environment.yml
          mamba-version: '*'
          use-mamba: true

      - name: Verify environment installation
        run: conda env list

      - id: 'auth'
        name: Authenticate for Google BigQuery access
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Update package download data
        run: ./cli/getdownloads.py

      - name: Update GitHub statistics
        run: ./cli/getghstats.py
        env:
          GITHUB_TOKEN: '${{ secrets.GRAPHQL_TOKEN }}'

      - name: Use pre-commit to fix newly generated data
        run: |
          conda install pre-commit
          pre-commit install
          pre-commit run --all || pre-commit run --all

      - name: Commit new changes
        uses: EndBug/add-and-commit@v8
        with:
          add: '-A'
          default_author: github_actions
          message: '[skip ci] Nightly metrics updates'

      - name: Build the book
        run: jupyter-book build .

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          enable_jekyll: false
